tabs:
  fields:
  
    # INCLUDE

    include_head:
        label: Head
        comment: Вставляет код в head секцию страницы
        default:
        size: large
        span: full
        type: textarea
        tab: Includes
        translatable: true
    include_body_begin:
        label: Body begin
        comment: Вставляет код в тело страницы сразу после <body>
        default:
        size: large
        span: full
        type: textarea
        tab: Includes
    include_body_end:
        label: Body end
        comment: Вставляет код в тело страницы перед </body>
        default:
        size: large
        span: full
        type: textarea
        tab: Includes
    robots:
        label: Robots.txt
        comment: "Доступны переменные: {{ url }} - адрес сайта, {{ backendUrl }} - админка"
        default:
        size: large
        span: full
        type: textarea
        tab: Includes

    # Site Settings

    site_section: 
        tab: Настройки сайта
        type: section
        label: Управление сайтом

    site_name:
        tab: Настройки сайта
        label: Название сайта
        default: Site

    # UI

    color_section: 
        tab: Внешний вид
        type: section
        label: Управление палитрой сайта

    colors:
        tab: Внешний вид
        type: nestedform
        showPanel: true
        form: ~/themes/uhdtv/themeColors.yaml