editor:
  name: Редактор
  description: Редактор
  icon: icon-list-alt
  fields:
    content:
      type: nestedform
      showPanel: false
      form: ~/themes/uhdtv/partials/components/editor/_.yaml

row:
  name: Колонки
  description: Колонки
  icon: icon-list-alt
  fields:
    content:
      type: nestedform
      showPanel: false
      form: ~/themes/uhdtv/partials/components/row/_.yaml

carousel:
  name: Карусель
  description: Карусель
  icon: icon-list-alt
  fields:
    content:
      type: nestedform
      showPanel: false
      form: ~/themes/uhdtv/partials/components/carousel/_.yaml

banner:
  name: Баннер
  description: Баннер
  icon: icon-list-alt
  fields:
    content:
      type: nestedform
      showPanel: false
      form: ~/themes/uhdtv/partials/components/banner/_.yaml

card:
  name: Карточка
  description: Карточка
  icon: icon-list-alt
  fields:
    content:
      type: nestedform
      showPanel: false
      form: ~/themes/uhdtv/partials/components/card/_.yaml

post:
  name: Пост
  description: Пост
  icon: icon-list-alt
  fields:
    content:
      type: nestedform
      showPanel: false
      form: ~/themes/uhdtv/partials/components/post/_.yaml

video:
  name: Видео
  description: Видео
  icon: icon-list-alt
  fields:
    content:
      type: nestedform
      showPanel: false
      form: ~/themes/uhdtv/partials/components/video/_.yaml

gallery:
  name: Галлерея
  description: Галлерея
  icon: icon-list-alt
  fields:
    content:
      type: nestedform
      showPanel: false
      form: ~/themes/uhdtv/partials/components/gallery/_.yaml

figure:
  name: Изображение c подписью
  description: Изображение c подписью
  icon: icon-list-alt
  fields:
    content:
      type: nestedform
      showPanel: false
      form: ~/themes/uhdtv/partials/components/figure/_.yaml

timer:
  name: Таймер
  description: Таймер
  icon: icon-list-alt
  fields:
    content:
      type: nestedform
      showPanel: false
      form: ~/themes/uhdtv/partials/components/timer/_.yaml

modal:
  name: Модальное окно
  description: Модальное окно
  icon: icon-list-alt
  fields:
    content:
      type: nestedform
      showPanel: false
      form: ~/themes/uhdtv/partials/components/modal/_.yaml
